### ISSUE TITLE
Unable to save image "enchan1207/buildroot"

### ISSUE THREAD

**Issue by Serhii-the-Dev** [Enchan1207/rpi-buildroot#15]
A test action created from the tutorial fails with an error:
```log
Run docker save "enchan1207/buildroot" -o "enchan1207-buildroot_base"
  docker save "enchan1207/buildroot" -o "enchan1207-buildroot_base"
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
Error response from daemon: No such image: enchan1207/buildroot
Error: Process completed with exit code 1.
```
Most likely the issue originates from this line:
https://github.com/Enchan1207/rpi-buildroot/blob/4f6ccf1ddd37594fcd112038c318540ef2af59e5/action.yml#L148
I'm assuming it should be something like that:
```sh
docker save "enchan1207/buildroot_base" -o "enchan1207-buildroot_base" 
```

**Comment by Enchan1207** [comment]
Thank you for reporting this issue.
The commit that modify container identifier from "enchan1207/buildroot" to "enchan1207/buildroot_base" was added.
